// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_SairaSemiCondensed_Medium_34_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  16,  24,  24,   2,  20,   0,   0, 0x00 }, // zero
    {   192, 0x0031,   9,  24,  24,   0,  11,   0,   0, 0x00 }, // one
    {   312, 0x0032,  16,  24,  24,   1,  18,   0,   0, 0x00 }, // two
    {   504, 0x0033,  15,  24,  24,   1,  18,   0,   0, 0x00 }, // three
    {   696, 0x0034,  17,  24,  24,   1,  19,   0,   0, 0x00 }, // four
    {   912, 0x0035,  15,  24,  24,   2,  18,   0,   0, 0x00 }, // five
    {  1104, 0x0036,  16,  24,  24,   2,  19,   0,   0, 0x00 }, // six
    {  1296, 0x0037,  15,  24,  24,   1,  17,   0,   0, 0x00 }, // seven
    {  1488, 0x0038,  17,  24,  24,   2,  20,   0,   0, 0x00 }, // eight
    {  1704, 0x0039,  17,  24,  24,   1,  19,   0,   0, 0x00 }, // nine
    {  1920, 0x003F,  12,  24,  24,   1,  15,   0,   0, 0x00 }  // question
};

// SairaSemiCondensed_Medium_34_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_SairaSemiCondensed_Medium_34_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_SairaSemiCondensed_Medium_34_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_SairaSemiCondensed_Medium_34_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_SairaSemiCondensed_Medium_34_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_SairaSemiCondensed_Medium_34_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_SairaSemiCondensed_Medium_34_4bpp();

touchgfx::GeneratedFont& getFont_SairaSemiCondensed_Medium_34_4bpp()
{
    static touchgfx::GeneratedFont SairaSemiCondensed_Medium_34_4bpp(glyphs_SairaSemiCondensed_Medium_34_4bpp, 11, 34, 34, 0, 0, 4, 1, 0, 0, unicodes_SairaSemiCondensed_Medium_34_4bpp, kerning_SairaSemiCondensed_Medium_34_4bpp, 63, 0, 0, 0);
    return SairaSemiCondensed_Medium_34_4bpp;
}
