// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_14_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   3,   0,   0, 0x00 }, // space
    {     0, 0x002B,   8,   8,   8,   0,   8,   0,   0, 0x00 }, // plus
    {    32, 0x002C,   4,   5,   3,  -1,   3,   0,   0, 0x00 }, // comma
    {    42, 0x002D,   5,   2,   5,   0,   4,   0,   0, 0x00 }, // hyphen
    {    48, 0x002E,   3,   3,   3,   0,   3,   0,   0, 0x00 }, // period
    {    54, 0x002F,   7,  12,  11,  -1,   5,   0,   0, 0x00 }, // slash
    {   102, 0x0030,   8,  11,  11,   0,   7,   0,   0, 0x00 }, // zero
    {   146, 0x0031,   7,  11,  11,   0,   7,   0,   0, 0x00 }, // one
    {   190, 0x0032,   7,  11,  11,   0,   7,   0,   0, 0x00 }, // two
    {   234, 0x0033,   7,  11,  11,   0,   7,   0,   0, 0x00 }, // three
    {   278, 0x0034,   8,  11,  11,   0,   7,   0,   0, 0x00 }, // four
    {   322, 0x0035,   7,  11,  11,   0,   7,   0,   0, 0x00 }, // five
    {   366, 0x0036,   8,  11,  11,   0,   7,   0,   0, 0x00 }, // six
    {   410, 0x0037,   7,  11,  11,   0,   7,   0,   0, 0x00 }, // seven
    {   454, 0x0038,   8,  11,  11,   0,   7,   0,   0, 0x00 }, // eight
    {   498, 0x0039,   7,  11,  11,   0,   7,   0,   0, 0x00 }, // nine
    {   542, 0x003A,   3,   8,   8,   0,   3,   0,   0, 0x00 }, // colon
    {   558, 0x003B,   4,  10,   8,  -1,   3,   0,   0, 0x00 }, // semicolon
    {   578, 0x003F,   7,  11,  11,   0,   6,   0,   0, 0x00 }, // question
    {   622, 0x0041,   9,  11,  11,   0,   9,   0,   0, 0x00 }, // A
    {   677, 0x0042,   7,  11,  11,   1,   8,   0,   0, 0x00 }, // B
    {   721, 0x0043,   9,  11,  11,   0,   9,   0,   0, 0x00 }, // C
    {   776, 0x0044,   9,  11,  11,   1,  10,   0,   0, 0x00 }, // D
    {   831, 0x0045,   7,  11,  11,   1,   8,   0,   0, 0x00 }, // E
    {   875, 0x0046,   6,  11,  11,   1,   7,   0,   0, 0x00 }, // F
    {   908, 0x0047,   9,  11,  11,   0,   9,   0,   0, 0x00 }, // G
    {   963, 0x0048,   9,  11,  11,   1,  10,   0,   0, 0x00 }, // H
    {  1018, 0x0049,   4,  11,  11,   0,   4,   0,   0, 0x00 }, // I
    {  1040, 0x004A,   5,  11,  11,   0,   6,   0,   0, 0x00 }, // J
    {  1073, 0x004B,   8,  11,  11,   1,   8,   0,   0, 0x00 }, // K
    {  1117, 0x004C,   6,  11,  11,   1,   7,   0,   0, 0x00 }, // L
    {  1150, 0x004D,  10,  11,  11,   1,  12,   0,   0, 0x00 }, // M
    {  1205, 0x004E,   9,  11,  11,   1,  10,   0,   0, 0x00 }, // N
    {  1260, 0x004F,  10,  11,  11,   0,  10,   0,   0, 0x00 }, // O
    {  1315, 0x0050,   7,  11,  11,   1,   8,   0,   0, 0x00 }, // P
    {  1359, 0x0051,  10,  13,  11,   0,  10,   0,   0, 0x00 }, // Q
    {  1424, 0x0052,   8,  11,  11,   1,   9,   0,   0, 0x00 }, // R
    {  1468, 0x0053,   7,  11,  11,   0,   7,   0,   0, 0x00 }, // S
    {  1512, 0x0054,   8,  11,  11,   0,   8,   0,   0, 0x00 }, // T
    {  1556, 0x0055,  10,  11,  11,   0,  10,   0,   0, 0x00 }, // U
    {  1611, 0x0056,   9,  11,  11,   0,   9,   0,   0, 0x00 }, // V
    {  1666, 0x0057,  13,  11,  11,   0,  12,   0,   0, 0x00 }, // W
    {  1743, 0x0058,   9,  11,  11,   0,   9,   0,   0, 0x00 }, // X
    {  1798, 0x0059,   8,  11,  11,   0,   8,   0,   0, 0x00 }, // Y
    {  1842, 0x005A,   9,  11,  11,   0,   9,   0,   0, 0x00 }, // Z
    {  1897, 0x00B0,   5,   4,  11,   0,   5,   0,   0, 0x00 }  // degree
};

// Asap_Bold_14_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_14_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_14_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_14_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_14_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_14_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_14_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_14_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_14_4bpp(glyphs_Asap_Bold_14_4bpp, 46, 16, 14, 0, 0, 4, 1, 1, 1, unicodes_Asap_Bold_14_4bpp, kerning_Asap_Bold_14_4bpp, 63, 0, 0, 0);
    return Asap_Bold_14_4bpp;
}
