// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_24_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x003A,   4,  11,  11,   1,   6,   0,   0, 0x00 }, // colon
    {    22, 0x003F,  12,  17,  17,   0,  12,   0,   1, 0x00 }, // question
    {   124, 0x0041,  15,  17,  17,   0,  15,   1,   1, 0x00 }, // A
    {   260, 0x004D,  19,  17,  17,   1,  21,   0,   0, 0x00 }, // M
    {   430, 0x0050,  12,  17,  17,   2,  14,   0,   0, 0x00 }  // P
};

// Exo2_Medium_24_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_24_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Exo2_Medium_24_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Exo2_Medium_24_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Exo2_Medium_24_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Exo2_Medium_24_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Exo2_Medium_24_4bpp();

touchgfx::GeneratedFont& getFont_Exo2_Medium_24_4bpp()
{
    static touchgfx::GeneratedFont Exo2_Medium_24_4bpp(glyphs_Exo2_Medium_24_4bpp, 5, 24, 24, 0, 0, 4, 1, 0, 0, unicodes_Exo2_Medium_24_4bpp, kerning_Exo2_Medium_24_4bpp, 63, 0, 0, 0);
    return Exo2_Medium_24_4bpp;
}
