/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/DeviceInfoWheelElementsBase.hpp>

DeviceInfoWheelElementsBase::DeviceInfoWheelElementsBase()
{
    setWidth(380);
    setHeight(124);
}

DeviceInfoWheelElementsBase::~DeviceInfoWheelElementsBase()
{

}

void DeviceInfoWheelElementsBase::initialize()
{

}
