// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_94_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  46,  68,  67,   2,  50,   0,   0, 0x00 }, // zero
    {  1564, 0x0031,  44,  66,  66,   3,  50,   0,   0, 0x00 }, // one
    {  3016, 0x0032,  43,  67,  67,   3,  50,   0,   0, 0x00 }, // two
    {  4490, 0x0033,  42,  68,  67,   3,  50,   0,   0, 0x00 }, // three
    {  5918, 0x0034,  49,  66,  66,   1,  50,   0,   0, 0x00 }, // four
    {  7568, 0x0035,  44,  67,  66,   3,  50,   0,   0, 0x00 }, // five
    {  9042, 0x0036,  45,  67,  66,   3,  50,   0,   0, 0x00 }, // six
    { 10583, 0x0037,  44,  66,  66,   3,  50,   0,   0, 0x00 }, // seven
    { 12035, 0x0038,  46,  68,  67,   2,  50,   0,   0, 0x00 }, // eight
    { 13599, 0x0039,  45,  68,  67,   2,  50,   0,   0, 0x00 }, // nine
    { 15163, 0x003F,  39,  67,  67,   3,  42,   0,   0, 0x00 }  // question
};

// Asap_Bold_94_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_94_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_94_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_94_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_94_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_94_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_94_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_94_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_94_4bpp(glyphs_Asap_Bold_94_4bpp, 11, 95, 94, 0, 0, 4, 1, 0, 0, unicodes_Asap_Bold_94_4bpp, kerning_Asap_Bold_94_4bpp, 63, 0, 0, 0);
    return Asap_Bold_94_4bpp;
}
