// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_30_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  16,  21,  21,   1,  18,   0,   0, 0x00 }, // zero
    {   168, 0x0031,   9,  21,  21,   0,  12,   0,   1, 0x00 }, // one
    {   273, 0x0032,  15,  21,  21,   1,  17,   0,   0, 0x00 }, // two
    {   441, 0x0033,  14,  21,  21,   1,  17,   0,   0, 0x00 }, // three
    {   588, 0x0034,  17,  21,  21,   1,  19,   1,   1, 0x00 }, // four
    {   777, 0x0035,  14,  21,  21,   1,  16,   0,   0, 0x00 }, // five
    {   924, 0x0036,  15,  21,  21,   1,  17,   0,   0, 0x00 }, // six
    {  1092, 0x0037,  14,  21,  21,   1,  15,   2,   1, 0x00 }, // seven
    {  1239, 0x0038,  15,  21,  21,   2,  18,   0,   0, 0x00 }, // eight
    {  1407, 0x0039,  15,  21,  21,   1,  17,   0,   0, 0x00 }, // nine
    {  1575, 0x003F,  13,  21,  21,   1,  15,   0,   0, 0x00 }  // question
};

// Exo2_Medium_30_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_30_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Exo2_Medium_30_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Exo2_Medium_30_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Exo2_Medium_30_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Exo2_Medium_30_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Exo2_Medium_30_4bpp();

touchgfx::GeneratedFont& getFont_Exo2_Medium_30_4bpp()
{
    static touchgfx::GeneratedFont Exo2_Medium_30_4bpp(glyphs_Exo2_Medium_30_4bpp, 11, 30, 30, 0, 0, 4, 1, 0, 0, unicodes_Exo2_Medium_30_4bpp, kerning_Exo2_Medium_30_4bpp, 63, 0, 0, 0);
    return Exo2_Medium_30_4bpp;
}
