// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Regular_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   6,   0,   0, 0x00 }, // space
    {     0, 0x003F,  10,  19,  19,   1,  12,   0,   0, 0x00 }, // question
    {    95, 0x0041,  16,  19,  19,   0,  16,   0,   0, 0x00 }, // A
    {   247, 0x0045,  11,  19,  19,   2,  14,   0,   0, 0x00 }, // E
    {   361, 0x004B,  14,  19,  19,   2,  15,   0,   0, 0x00 }, // K
    {   494, 0x004D,  18,  19,  19,   2,  22,   0,   0, 0x00 }, // M
    {   665, 0x004F,  17,  19,  19,   1,  19,   0,   0, 0x00 }, // O
    {   836, 0x0050,  13,  19,  19,   2,  15,   0,   0, 0x00 }, // P
    {   969, 0x0054,  14,  19,  19,   0,  14,   0,   0, 0x00 }, // T
    {  1102, 0x0055,  15,  19,  19,   2,  19,   0,   0, 0x00 }, // U
    {  1254, 0x0057,  23,  19,  19,   0,  23,   0,   0, 0x00 }  // W
};

// Asap_Regular_26_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Regular_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Regular_26_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Regular_26_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Regular_26_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Regular_26_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Regular_26_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Regular_26_4bpp()
{
    static touchgfx::GeneratedFont Asap_Regular_26_4bpp(glyphs_Asap_Regular_26_4bpp, 11, 26, 26, 0, 0, 4, 1, 0, 1, unicodes_Asap_Regular_26_4bpp, kerning_Asap_Regular_26_4bpp, 63, 0, 0, 0);
    return Asap_Regular_26_4bpp;
}
