/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/HomeUIWheelLargeElementsBase.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>

HomeUIWheelLargeElementsBase::HomeUIWheelLargeElementsBase()
{
    setWidth(120);
    setHeight(135);
    textAreaBottomlineLarge.setPosition(24, 120, 73, 14);
    textAreaBottomlineLarge.setColor(touchgfx::Color::getColorFromRGB(52, 75, 103));
    textAreaBottomlineLarge.setLinespacing(0);
    textAreaBottomlineLarge.setTypedText(touchgfx::TypedText(T_HOMEUIWHEELHEATINGUPCENTER));
    add(textAreaBottomlineLarge);

    textAreaDevicesLarge.setPosition(26, 56, 69, 70);
    textAreaDevicesLarge.setColor(touchgfx::Color::getColorFromRGB(52, 75, 101));
    textAreaDevicesLarge.setLinespacing(0);
    Unicode::snprintf(textAreaDevicesLargeBuffer, TEXTAREADEVICESLARGE_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_5KEZ).getText());
    textAreaDevicesLarge.setWildcard(textAreaDevicesLargeBuffer);
    textAreaDevicesLarge.setTypedText(touchgfx::TypedText(T___SINGLEUSE_SAQX));
    add(textAreaDevicesLarge);

    textAreaRoomLarge.setPosition(0, 3, 120, 19);
    textAreaRoomLarge.setColor(touchgfx::Color::getColorFromRGB(52, 75, 101));
    textAreaRoomLarge.setLinespacing(0);
    textAreaRoomLarge.setTypedText(touchgfx::TypedText(T_HOMEUIWHEELBATHROOMSELECTED));
    add(textAreaRoomLarge);

    imageSliderLarge.setXY(0, 35);
    imageSliderLarge.setBitmap(touchgfx::Bitmap(BITMAP_MAIN_SLIDER_TEMP_ID));
    add(imageSliderLarge);

    textAreaDegreeLarge.setXY(54, 48);
    textAreaDegreeLarge.setColor(touchgfx::Color::getColorFromRGB(46, 64, 86));
    textAreaDegreeLarge.setLinespacing(0);
    textAreaDegreeLarge.setTypedText(touchgfx::TypedText(T___SINGLEUSE_TJYI));
    add(textAreaDegreeLarge);
}

HomeUIWheelLargeElementsBase::~HomeUIWheelLargeElementsBase()
{

}

void HomeUIWheelLargeElementsBase::initialize()
{

}
