// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_Semibold_20_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   5,   0,   0, 0x00 }, // space
    {     0, 0x002C,   4,   5,   2,   0,   5,   0,   6, 0x00 }, // comma
    {    10, 0x0034,  12,  14,  14,   0,  11,   0,   0, 0x00 }, // four
    {    94, 0x003F,   9,  14,  14,   0,   9,   0,   0, 0x00 }, // question
    {   164, 0x0041,  14,  14,  14,   0,  13,   6,   3, 0x00 }, // A
    {   262, 0x0042,  12,  14,  14,   1,  13,   0,   0, 0x00 }, // B
    {   346, 0x0043,  11,  14,  14,   1,  13,   9,   1, 0x00 }, // C
    {   430, 0x0044,  13,  14,  14,   1,  15,   0,   0, 0x00 }, // D
    {   528, 0x0045,   9,  14,  14,   1,  11,   0,   0, 0x00 }, // E
    {   598, 0x0047,  12,  14,  14,   1,  15,  10,   1, 0x00 }, // G
    {   682, 0x0048,  13,  14,  14,   1,  15,   0,   0, 0x00 }, // H
    {   780, 0x0049,   4,  14,  14,   1,   6,   0,   0, 0x00 }, // I
    {   808, 0x004B,  12,  14,  14,   1,  13,   0,   0, 0x00 }, // K
    {   892, 0x004C,  10,  14,  14,   1,  11,   0,   0, 0x00 }, // L
    {   962, 0x004E,  13,  14,  14,   1,  16,   0,   0, 0x00 }, // N
    {  1060, 0x004F,  14,  14,  14,   1,  16,  11,   1, 0x00 }, // O
    {  1158, 0x0050,  11,  14,  14,   1,  12,   0,   0, 0x00 }, // P
    {  1242, 0x0052,  12,  14,  14,   1,  13,   0,   0, 0x00 }, // R
    {  1326, 0x0053,  10,  14,  14,   1,  11,   0,   0, 0x00 }, // S
    {  1396, 0x0054,  11,  14,  14,   0,  11,  12,   2, 0x00 }, // T
    {  1480, 0x0055,  13,  14,  14,   1,  15,   0,   0, 0x00 }, // U
    {  1578, 0x0057,  19,  14,  14,   0,  19,  14,   2, 0x00 }, // W
    {  1718, 0x005A,  11,  14,  14,   0,  12,   0,   0, 0x00 }  // Z
};

// OpenSans_Semibold_20_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_Semibold_20_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_OpenSans_Semibold_20_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_OpenSans_Semibold_20_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_OpenSans_Semibold_20_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_OpenSans_Semibold_20_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_OpenSans_Semibold_20_4bpp();

touchgfx::GeneratedFont& getFont_OpenSans_Semibold_20_4bpp()
{
    static touchgfx::GeneratedFont OpenSans_Semibold_20_4bpp(glyphs_OpenSans_Semibold_20_4bpp, 23, 23, 20, 0, 0, 4, 1, 0, 1, unicodes_OpenSans_Semibold_20_4bpp, kerning_OpenSans_Semibold_20_4bpp, 63, 0, 0, 0);
    return OpenSans_Semibold_20_4bpp;
}
