// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_Semibold_23_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  12,  17,  17,   1,  13,   0,   0, 0x00 }, // zero
    {   102, 0x0031,   8,  17,  17,   1,  13,   0,   0, 0x00 }, // one
    {   170, 0x0032,  12,  17,  17,   1,  13,   0,   0, 0x00 }, // two
    {   272, 0x0033,  11,  17,  17,   1,  13,   0,   0, 0x00 }, // three
    {   374, 0x0034,  13,  17,  17,   0,  13,   0,   0, 0x00 }, // four
    {   493, 0x0035,  11,  17,  17,   1,  13,   0,   0, 0x00 }, // five
    {   595, 0x0036,  12,  17,  17,   1,  13,   0,   0, 0x00 }, // six
    {   697, 0x0037,  13,  17,  17,   0,  13,   0,   0, 0x00 }, // seven
    {   816, 0x0038,  12,  17,  17,   1,  13,   0,   0, 0x00 }, // eight
    {   918, 0x0039,  12,  17,  17,   1,  13,   0,   0, 0x00 }, // nine
    {  1020, 0x003F,  10,  17,  17,   0,  10,   0,   0, 0x00 }  // question
};

// OpenSans_Semibold_23_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_Semibold_23_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_OpenSans_Semibold_23_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_OpenSans_Semibold_23_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_OpenSans_Semibold_23_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_OpenSans_Semibold_23_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_OpenSans_Semibold_23_4bpp();

touchgfx::GeneratedFont& getFont_OpenSans_Semibold_23_4bpp()
{
    static touchgfx::GeneratedFont OpenSans_Semibold_23_4bpp(glyphs_OpenSans_Semibold_23_4bpp, 11, 23, 23, 0, 0, 4, 1, 0, 0, unicodes_OpenSans_Semibold_23_4bpp, kerning_OpenSans_Semibold_23_4bpp, 63, 0, 0, 0);
    return OpenSans_Semibold_23_4bpp;
}
