// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_SemiBold_25_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   6,   0,   3, 0x00 }, // space
    {     0, 0x002B,  12,  12,  14,   1,  14,   0,   0, 0x00 }, // plus
    {    72, 0x0030,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // zero
    {   198, 0x0031,   8,  18,  18,   0,  10,   3,   2, 0x00 }, // one
    {   270, 0x0032,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // two
    {   378, 0x0033,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // three
    {   486, 0x0034,  15,  18,  18,   0,  16,   5,   2, 0x00 }, // four
    {   630, 0x0035,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // five
    {   738, 0x0036,  13,  18,  18,   1,  14,   0,   0, 0x00 }, // six
    {   864, 0x0037,  13,  18,  18,   0,  13,   7,   4, 0x00 }, // seven
    {   990, 0x0038,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // eight
    {  1116, 0x0039,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // nine
    {  1224, 0x003F,  12,  18,  18,   0,  13,  11,   4, 0x00 }, // question
    {  1332, 0x0041,  16,  18,  18,   0,  16,  15,   5, 0x00 }, // A
    {  1476, 0x0042,  14,  18,  18,   1,  16,   0,   0, 0x00 }, // B
    {  1602, 0x0043,  13,  18,  18,   1,  14,   0,   0, 0x00 }, // C
    {  1728, 0x0045,  13,  18,  18,   1,  14,   0,   0, 0x00 }, // E
    {  1854, 0x0046,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // F
    {  1962, 0x0047,  14,  18,  18,   1,  16,   0,   0, 0x00 }, // G
    {  2088, 0x0048,  14,  18,  18,   1,  17,   0,   0, 0x00 }, // H
    {  2214, 0x0049,   5,  18,  18,   1,   7,   0,   0, 0x00 }, // I
    {  2268, 0x004C,  12,  18,  18,   1,  13,   0,   0, 0x00 }, // L
    {  2376, 0x004D,  20,  18,  18,   1,  22,   0,   0, 0x00 }, // M
    {  2556, 0x004E,  15,  18,  18,   1,  18,   0,   0, 0x00 }, // N
    {  2700, 0x004F,  15,  18,  18,   1,  17,   0,   0, 0x00 }, // O
    {  2844, 0x0050,  14,  18,  18,   1,  15,   0,   0, 0x00 }, // P
    {  2970, 0x0052,  14,  18,  18,   1,  16,   0,   0, 0x00 }, // R
    {  3096, 0x0053,  13,  18,  18,   1,  14,   0,   0, 0x00 }, // S
    {  3222, 0x0054,  15,  18,  18,   0,  15,  20,   5, 0x00 }, // T
    {  3366, 0x0068,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // h
    {  3492, 0x006D,  20,  13,  13,   1,  22,  25,   1, 0x00 }, // m
    {  3622, 0x00B0,   7,   7,  18,   1,   9,   0,   0, 0x00 }  // degree
};

// Exo2_SemiBold_25_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_SemiBold_25_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Exo2_SemiBold_25_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Exo2_SemiBold_25_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Exo2_SemiBold_25_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Exo2_SemiBold_25_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Exo2_SemiBold_25_4bpp();

touchgfx::GeneratedFont& getFont_Exo2_SemiBold_25_4bpp()
{
    static touchgfx::GeneratedFont Exo2_SemiBold_25_4bpp(glyphs_Exo2_SemiBold_25_4bpp, 32, 25, 25, 0, 0, 4, 1, 0, 0, unicodes_Exo2_SemiBold_25_4bpp, kerning_Exo2_SemiBold_25_4bpp, 63, 0, 0, 0);
    return Exo2_SemiBold_25_4bpp;
}
