// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_25_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x003F,  11,  17,  17,   0,  11,   0,   0, 0x00 }, // question
    {   102, 0x0046,  11,  17,  17,   1,  13,   0,   0, 0x00 }, // F
    {   204, 0x00B0,   7,   7,  18,   1,   9,   0,   0, 0x00 }  // degree
};

// Asap_Bold_25_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_25_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_25_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_25_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_25_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_25_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_25_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_25_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_25_4bpp(glyphs_Asap_Bold_25_4bpp, 3, 25, 25, 0, 0, 4, 1, 0, 0, unicodes_Asap_Bold_25_4bpp, kerning_Asap_Bold_25_4bpp, 63, 0, 0, 0);
    return Asap_Bold_25_4bpp;
}
