/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/BathtubWheelElementBase.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <touchgfx/Color.hpp>

BathtubWheelElementBase::BathtubWheelElementBase()
{
    setWidth(138);
    setHeight(48);
    elementValue.setPosition(44, 9, 50, 37);
    elementValue.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    elementValue.setLinespacing(0);
    Unicode::snprintf(elementValueBuffer, ELEMENTVALUE_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_2TYP).getText());
    elementValue.setWildcard(elementValueBuffer);
    elementValue.setTypedText(touchgfx::TypedText(T___SINGLEUSE_7FW7));
    add(elementValue);
}

BathtubWheelElementBase::~BathtubWheelElementBase()
{

}

void BathtubWheelElementBase::initialize()
{

}
