// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_60_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  30,  42,  42,   1,  32,   0,   0, 0x00 }, // zero
    {   630, 0x0031,  28,  42,  42,   2,  32,   0,   0, 0x00 }, // one
    {  1218, 0x0032,  28,  42,  42,   2,  32,   0,   0, 0x00 }, // two
    {  1806, 0x0033,  27,  42,  42,   2,  32,   0,   0, 0x00 }, // three
    {  2394, 0x0034,  32,  42,  42,   0,  32,   0,   0, 0x00 }, // four
    {  3066, 0x0035,  28,  42,  42,   2,  32,   0,   0, 0x00 }, // five
    {  3654, 0x0036,  29,  42,  42,   2,  32,   0,   0, 0x00 }, // six
    {  4284, 0x0037,  28,  42,  42,   2,  32,   0,   0, 0x00 }, // seven
    {  4872, 0x0038,  30,  42,  42,   1,  32,   0,   0, 0x00 }, // eight
    {  5502, 0x0039,  29,  42,  42,   1,  32,   0,   0, 0x00 }, // nine
    {  6132, 0x003F,  25,  42,  42,   2,  27,   0,   0, 0x00 }  // question
};

// Asap_Bold_60_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_60_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_60_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_60_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_60_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_60_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_60_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_60_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_60_4bpp(glyphs_Asap_Bold_60_4bpp, 11, 60, 60, 0, 0, 4, 1, 0, 0, unicodes_Asap_Bold_60_4bpp, kerning_Asap_Bold_60_4bpp, 63, 0, 0, 0);
    return Asap_Bold_60_4bpp;
}
