/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/BathtubWheelElementCenterBase.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <touchgfx/Color.hpp>

BathtubWheelElementCenterBase::BathtubWheelElementCenterBase()
{
    setWidth(138);
    setHeight(48);
    elementValue.setPosition(44, 6, 50, 37);
    elementValue.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    elementValue.setLinespacing(0);
    Unicode::snprintf(elementValueBuffer, ELEMENTVALUE_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_H7JZ).getText());
    elementValue.setWildcard(elementValueBuffer);
    elementValue.setTypedText(touchgfx::TypedText(T___SINGLEUSE_GG1M));
    add(elementValue);
}

BathtubWheelElementCenterBase::~BathtubWheelElementCenterBase()
{

}

void BathtubWheelElementCenterBase::initialize()
{

}
