/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/RecipeListElementBase.hpp>
#include <images/BitmapDatabase.hpp>
#include <touchgfx/Color.hpp>
#include <texts/TextKeysAndLanguages.hpp>

RecipeListElementBase::RecipeListElementBase()
{
    setWidth(480);
    setHeight(75);
    imageRecipe.setXY(5, 5);
    imageRecipe.setBitmap(touchgfx::Bitmap(BITMAP_PASTA_01_ID));
    add(imageRecipe);

    boxLine.setPosition(125, 2, 335, 1);
    boxLine.setColor(touchgfx::Color::getColorFromRGB(72, 53, 43));
    boxLine.setVisible(false);
    add(boxLine);

    textAreaRecipeHeadline.setPosition(124, 8, 325, 28);
    textAreaRecipeHeadline.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    textAreaRecipeHeadline.setLinespacing(0);
    textAreaRecipeHeadline.setTypedText(touchgfx::TypedText(T_RECIPEHEADLINE1));
    add(textAreaRecipeHeadline);

    textAreaRecipeText.setPosition(124, 35, 325, 36);
    textAreaRecipeText.setColor(touchgfx::Color::getColorFromRGB(157, 123, 100));
    textAreaRecipeText.setLinespacing(0);
    textAreaRecipeText.setTypedText(touchgfx::TypedText(T_RECIPETEXT1));
    add(textAreaRecipeText);
}

RecipeListElementBase::~RecipeListElementBase()
{

}

void RecipeListElementBase::initialize()
{

}
