// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_10_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   2,   0,   0, 0x00 }, // space
    {     0, 0x0030,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // zero
    {    21, 0x0031,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // one
    {    42, 0x0032,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // two
    {    63, 0x0033,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // three
    {    84, 0x0034,   6,   7,   7,   0,   5,   0,   0, 0x00 }, // four
    {   105, 0x0035,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // five
    {   126, 0x0036,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // six
    {   147, 0x0037,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // seven
    {   168, 0x0038,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // eight
    {   189, 0x0039,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // nine
    {   210, 0x003F,   5,   7,   7,   0,   4,   0,   0, 0x00 }, // question
    {   231, 0x0041,   7,   7,   7,   0,   6,   0,   0, 0x00 }, // A
    {   259, 0x0043,   6,   7,   7,   0,   6,   0,   0, 0x00 }, // C
    {   280, 0x0044,   7,   7,   7,   0,   7,   0,   0, 0x00 }, // D
    {   308, 0x0045,   6,   7,   7,   0,   5,   0,   0, 0x00 }, // E
    {   329, 0x0047,   7,   7,   7,   0,   7,   0,   0, 0x00 }, // G
    {   357, 0x0048,   7,   7,   7,   0,   7,   0,   0, 0x00 }, // H
    {   385, 0x0049,   3,   7,   7,   0,   3,   0,   0, 0x00 }, // I
    {   399, 0x004C,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // L
    {   420, 0x004E,   7,   7,   7,   0,   7,   0,   0, 0x00 }, // N
    {   448, 0x0050,   6,   7,   7,   0,   6,   0,   0, 0x00 }, // P
    {   469, 0x0053,   5,   7,   7,   0,   5,   0,   0, 0x00 }, // S
    {   490, 0x0054,   6,   7,   7,   0,   5,   0,   0, 0x00 }, // T
    {   511, 0x0055,   7,   7,   7,   0,   7,   0,   0, 0x00 }, // U
    {   539, 0x0056,   6,   7,   7,   0,   6,   0,   0, 0x00 }  // V
};

// Asap_Bold_10_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_10_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_10_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_10_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_10_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_10_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_10_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_10_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_10_4bpp(glyphs_Asap_Bold_10_4bpp, 26, 10, 10, 0, 0, 4, 1, 0, 1, unicodes_Asap_Bold_10_4bpp, kerning_Asap_Bold_10_4bpp, 63, 0, 0, 0);
    return Asap_Bold_10_4bpp;
}
