// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_18_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   4,   0,   0, 0x00 }, // space
    {     0, 0x003F,   9,  12,  12,   0,   9,   0,   1, 0x00 }, // question
    {    60, 0x0041,  11,  12,  12,   0,  11,   1,   2, 0x00 }, // A
    {   132, 0x0045,   9,  12,  12,   1,  10,   0,   0, 0x00 }, // E
    {   192, 0x0048,  10,  12,  12,   1,  12,   0,   0, 0x00 }, // H
    {   252, 0x004E,  11,  12,  12,   1,  13,   0,   0, 0x00 }, // N
    {   324, 0x004F,  10,  12,  12,   1,  12,   0,   0, 0x00 }, // O
    {   384, 0x0054,  11,  12,  12,   0,  11,   3,   1, 0x00 }, // T
    {   456, 0x0056,  11,  12,  12,   0,  11,   4,   1, 0x00 }  // V
};

// Exo2_Medium_18_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_18_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Exo2_Medium_18_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Exo2_Medium_18_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Exo2_Medium_18_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Exo2_Medium_18_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Exo2_Medium_18_4bpp();

touchgfx::GeneratedFont& getFont_Exo2_Medium_18_4bpp()
{
    static touchgfx::GeneratedFont Exo2_Medium_18_4bpp(glyphs_Exo2_Medium_18_4bpp, 9, 18, 18, 0, 0, 4, 1, 0, 0, unicodes_Exo2_Medium_18_4bpp, kerning_Exo2_Medium_18_4bpp, 63, 0, 0, 0);
    return Exo2_Medium_18_4bpp;
}
