// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_SemiboldItalic_13_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   3,   0,   0, 0x00 }, // space
    {     0, 0x0026,   9,   9,   9,   0,   9,   0,   0, 0x00 }, // ampersand
    {    45, 0x0027,   3,   4,   9,   1,   3,   0,   0, 0x00 }, // quotesingle
    {    53, 0x002C,   4,   3,   1,  -1,   3,   0,   0, 0x00 }, // comma
    {    59, 0x002D,   4,   2,   4,   0,   4,   0,   0, 0x00 }, // hyphen
    {    63, 0x002E,   3,   2,   2,   0,   4,   0,   0, 0x00 }, // period
    {    67, 0x003F,   6,   9,   9,   1,   6,   0,   0, 0x00 }, // question
    {    94, 0x0041,   8,   9,   9,  -1,   8,   0,   0, 0x00 }, // A
    {   130, 0x0043,   9,   9,   9,   0,   8,   0,   0, 0x00 }, // C
    {   175, 0x0048,   9,   9,   9,   0,   9,   0,   0, 0x00 }, // H
    {   220, 0x0049,   4,   9,   9,   0,   4,   0,   0, 0x00 }, // I
    {   238, 0x0053,   7,   9,   9,   0,   7,   0,   0, 0x00 }, // S
    {   274, 0x0054,   7,   9,   9,   1,   7,   0,   0, 0x00 }, // T
    {   310, 0x0061,   8,   7,   7,   0,   8,   0,   1, 0x00 }, // a
    {   338, 0x0062,   7,  10,  10,   0,   8,   0,   0, 0x00 }, // b
    {   378, 0x0063,   7,   7,   7,   0,   6,   0,   0, 0x00 }, // c
    {   406, 0x0064,   8,  10,  10,   0,   8,   0,   0, 0x00 }, // d
    {   446, 0x0065,   7,   7,   7,   0,   7,   0,   0, 0x00 }, // e
    {   474, 0x0066,   8,  13,  10,  -2,   4,   0,   0, 0x00 }, // f
    {   526, 0x0067,   9,  10,   7,  -1,   7,   0,   0, 0x00 }, // g
    {   576, 0x0068,   7,  10,  10,   0,   8,   0,   0, 0x00 }, // h
    {   616, 0x0069,   4,  10,  10,   0,   4,   0,   0, 0x00 }, // i
    {   636, 0x006A,   6,  13,  10,  -2,   4,   0,   0, 0x00 }, // j
    {   675, 0x006B,   8,  10,  10,   0,   7,   0,   0, 0x00 }, // k
    {   715, 0x006C,   4,  10,  10,   0,   4,   0,   0, 0x00 }, // l
    {   735, 0x006D,  11,   7,   7,   0,  12,   0,   0, 0x00 }, // m
    {   777, 0x006E,   7,   7,   7,   0,   8,   0,   0, 0x00 }, // n
    {   805, 0x006F,   7,   7,   7,   0,   7,   0,   0, 0x00 }, // o
    {   833, 0x0070,   8,  10,   7,  -1,   8,   0,   0, 0x00 }, // p
    {   873, 0x0071,   8,  10,   7,   0,   8,   0,   0, 0x00 }, // q
    {   913, 0x0072,   6,   7,   7,   0,   5,   0,   0, 0x00 }, // r
    {   934, 0x0073,   6,   7,   7,   0,   6,   0,   0, 0x00 }, // s
    {   955, 0x0074,   5,   9,   9,   0,   5,   0,   0, 0x00 }, // t
    {   982, 0x0075,   8,   7,   7,   0,   8,   0,   0, 0x00 }, // u
    {  1010, 0x0076,   7,   7,   7,   0,   6,   0,   0, 0x00 }, // v
    {  1038, 0x0077,  11,   7,   7,   0,  10,   0,   0, 0x00 }, // w
    {  1080, 0x0079,   9,  10,   7,  -2,   6,   0,   0, 0x00 }, // y
    {  1130, 0x007A,   7,   7,   7,  -1,   6,   0,   0, 0x00 }  // z
};

// OpenSans_SemiboldItalic_13_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_SemiboldItalic_13_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_OpenSans_SemiboldItalic_13_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_OpenSans_SemiboldItalic_13_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_OpenSans_SemiboldItalic_13_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_OpenSans_SemiboldItalic_13_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_OpenSans_SemiboldItalic_13_4bpp();

touchgfx::GeneratedFont& getFont_OpenSans_SemiboldItalic_13_4bpp()
{
    static touchgfx::GeneratedFont OpenSans_SemiboldItalic_13_4bpp(glyphs_OpenSans_SemiboldItalic_13_4bpp, 38, 16, 13, 0, 0, 4, 1, 2, 2, unicodes_OpenSans_SemiboldItalic_13_4bpp, kerning_OpenSans_SemiboldItalic_13_4bpp, 63, 0, 0, 0);
    return OpenSans_SemiboldItalic_13_4bpp;
}
