// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_16_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   4,   0,   0, 0x00 }, // space
    {     0, 0x0030,   9,  12,  12,   0,   9,   0,   0, 0x00 }, // zero
    {    60, 0x0031,   8,  12,  12,   0,   9,   0,   0, 0x00 }, // one
    {   108, 0x0032,   8,  12,  12,   0,   9,   0,   0, 0x00 }, // two
    {   156, 0x0033,   8,  12,  12,   0,   9,   0,   0, 0x00 }, // three
    {   204, 0x0034,   9,  12,  12,   0,   9,   0,   0, 0x00 }, // four
    {   264, 0x0035,   8,  12,  12,   0,   9,   0,   0, 0x00 }, // five
    {   312, 0x0036,   9,  12,  12,   0,   9,   0,   0, 0x00 }, // six
    {   372, 0x0037,   8,  12,  12,   0,   9,   0,   0, 0x00 }, // seven
    {   420, 0x0038,   9,  12,  12,   0,   9,   0,   0, 0x00 }, // eight
    {   480, 0x0039,   8,  12,  12,   0,   9,   0,   0, 0x00 }, // nine
    {   528, 0x003F,   7,  12,  12,   0,   7,   0,   0, 0x00 }, // question
    {   576, 0x0041,  10,  12,  12,   0,  10,   0,   0, 0x00 }, // A
    {   636, 0x0043,  10,  12,  12,   0,  10,   0,   0, 0x00 }, // C
    {   696, 0x0044,  10,  12,  12,   1,  11,   0,   0, 0x00 }, // D
    {   756, 0x0045,   8,  12,  12,   1,   9,   0,   0, 0x00 }, // E
    {   804, 0x0046,   7,  12,  12,   1,   8,   0,   0, 0x00 }, // F
    {   852, 0x0047,  10,  12,  12,   0,  11,   0,   0, 0x00 }, // G
    {   912, 0x0048,  10,  12,  12,   1,  12,   0,   0, 0x00 }, // H
    {   972, 0x0049,   3,  12,  12,   1,   5,   0,   0, 0x00 }, // I
    {   996, 0x004B,   9,  12,  12,   1,   9,   0,   0, 0x00 }, // K
    {  1056, 0x004C,   7,  12,  12,   1,   8,   0,   0, 0x00 }, // L
    {  1104, 0x004E,  10,  12,  12,   1,  12,   0,   0, 0x00 }, // N
    {  1164, 0x004F,  11,  12,  12,   0,  12,   0,   0, 0x00 }, // O
    {  1236, 0x0050,   8,  12,  12,   1,   9,   0,   0, 0x00 }, // P
    {  1284, 0x0052,   9,  12,  12,   1,  10,   0,   0, 0x00 }, // R
    {  1344, 0x0053,   8,  12,  12,   0,   8,   0,   0, 0x00 }, // S
    {  1392, 0x0054,   9,  12,  12,   0,   9,   0,   0, 0x00 }, // T
    {  1452, 0x0055,  10,  12,  12,   1,  11,   0,   0, 0x00 }, // U
    {  1512, 0x0057,  15,  12,  12,   0,  14,   0,   0, 0x00 }, // W
    {  1608, 0x0059,   9,  12,  12,   0,   9,   0,   0, 0x00 }  // Y
};

// Asap_Bold_16_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_16_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_16_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_16_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_16_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_16_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_16_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_16_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_16_4bpp(glyphs_Asap_Bold_16_4bpp, 31, 16, 16, 0, 0, 4, 1, 0, 1, unicodes_Asap_Bold_16_4bpp, kerning_Asap_Bold_16_4bpp, 63, 0, 0, 0);
    return Asap_Bold_16_4bpp;
}
