// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_22_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  12,  16,  16,   0,  12,   0,   0, 0x00 }, // zero
    {    96, 0x0031,  11,  16,  16,   0,  12,   0,   0, 0x00 }, // one
    {   192, 0x0032,  11,  16,  16,   0,  12,   0,   0, 0x00 }, // two
    {   288, 0x0033,  11,  16,  16,   0,  12,   0,   0, 0x00 }, // three
    {   384, 0x0034,  12,  16,  16,   0,  12,   0,   0, 0x00 }, // four
    {   480, 0x0035,  11,  16,  16,   0,  12,   0,   0, 0x00 }, // five
    {   576, 0x0036,  12,  16,  16,   0,  12,   0,   0, 0x00 }, // six
    {   672, 0x0037,  11,  16,  16,   0,  12,   0,   0, 0x00 }, // seven
    {   768, 0x0038,  12,  16,  16,   0,  12,   0,   0, 0x00 }, // eight
    {   864, 0x0039,  11,  16,  16,   0,  12,   0,   0, 0x00 }, // nine
    {   960, 0x003F,  10,  16,  16,   0,  10,   0,   0, 0x00 }  // question
};

// Asap_Bold_22_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_22_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_22_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_22_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_22_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_22_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_22_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_22_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_22_4bpp(glyphs_Asap_Bold_22_4bpp, 11, 22, 22, 0, 0, 4, 1, 0, 0, unicodes_Asap_Bold_22_4bpp, kerning_Asap_Bold_22_4bpp, 63, 0, 0, 0);
    return Asap_Bold_22_4bpp;
}
