// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  14,  18,  18,   1,  16,   0,   0, 0x00 }, // zero
    {   126, 0x0031,   8,  18,  18,   0,  10,   0,   0, 0x00 }, // one
    {   198, 0x0032,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // two
    {   324, 0x0033,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // three
    {   432, 0x0034,  14,  18,  18,   1,  16,   0,   0, 0x00 }, // four
    {   558, 0x0035,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // five
    {   666, 0x0036,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // six
    {   792, 0x0037,  12,  18,  18,   1,  13,   0,   1, 0x00 }, // seven
    {   900, 0x0038,  14,  18,  18,   1,  16,   0,   0, 0x00 }, // eight
    {  1026, 0x0039,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // nine
    {  1152, 0x003F,  12,  18,  18,   1,  13,   0,   0, 0x00 }  // question
};

// Exo2_Medium_26_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Exo2_Medium_26_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Exo2_Medium_26_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Exo2_Medium_26_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Exo2_Medium_26_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Exo2_Medium_26_4bpp();

touchgfx::GeneratedFont& getFont_Exo2_Medium_26_4bpp()
{
    static touchgfx::GeneratedFont Exo2_Medium_26_4bpp(glyphs_Exo2_Medium_26_4bpp, 11, 26, 26, 0, 0, 4, 1, 0, 0, unicodes_Exo2_Medium_26_4bpp, kerning_Exo2_Medium_26_4bpp, 63, 0, 0, 0);
    return Exo2_Medium_26_4bpp;
}
