/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef OVENSPLASHSCREENBASE_HPP
#define OVENSPLASHSCREENBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <touchgfx/containers/Container.hpp>
#include <touchgfx/widgets/Image.hpp>
#include <touchgfx/widgets/TextArea.hpp>
#include <touchgfx/containers/buttons/Buttons.hpp>

class OvenSplashScreenBase : public touchgfx::Container
{
public:
    OvenSplashScreenBase();
    virtual ~OvenSplashScreenBase();
    virtual void initialize();

    /*
     * Virtual Action Handlers
     */
    virtual void screenIsPressed()
    {
        // Override and implement this function in OvenSplashScreen
    }

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Image background;
    touchgfx::TextArea textAreaHour;
    touchgfx::TextArea textAreaMinute;
    touchgfx::TextArea textAreaDivider;
    touchgfx::TextArea textAreaAmPm;
    touchgfx::ImageButtonStyle< touchgfx::IconButtonStyle< touchgfx::ClickButtonTrigger >  >  powerButton;

private:

    /*
     * Callback Declarations
     */
    touchgfx::Callback<OvenSplashScreenBase, const touchgfx::AbstractButtonContainer&> flexButtonCallback;

    /*
     * Callback Handler Declarations
     */
    void flexButtonCallbackHandler(const touchgfx::AbstractButtonContainer& src);

};

#endif // OVENSPLASHSCREENBASE_HPP
