/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/RoomInfoBase.hpp>
#include <images/BitmapDatabase.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <touchgfx/Color.hpp>

RoomInfoBase::RoomInfoBase()
{
    setWidth(390);
    setHeight(146);
    swipeBG.setXY(-45, 0);
    swipeBG.setBitmap(touchgfx::Bitmap(BITMAP_SELECTEDTEMPBG_ID));
    add(swipeBG);

    imageAirHumidty.setXY(11, 42);
    imageAirHumidty.setBitmap(touchgfx::Bitmap(BITMAP_INFO_AIR_HUMIDITY_ID));
    add(imageAirHumidty);

    textAreaAirHum.setXY(11, 12);
    textAreaAirHum.setColor(touchgfx::Color::getColorFromRGB(77, 108, 139));
    textAreaAirHum.setLinespacing(0);
    textAreaAirHum.setTypedText(touchgfx::TypedText(T_HOMEUIINFO));
    add(textAreaAirHum);

    containerLarge.setPosition(130, 7, 123, 134);
    textAreaBottomlineLarge.setPosition(27, 120, 73, 14);
    textAreaBottomlineLarge.setColor(touchgfx::Color::getColorFromRGB(52, 75, 103));
    textAreaBottomlineLarge.setLinespacing(0);
    textAreaBottomlineLarge.setTypedText(touchgfx::TypedText(T_HOMEUIWHEELHEATINGUPCENTER));
    containerLarge.add(textAreaBottomlineLarge);

    textAreaDevicesLarge.setPosition(29, 55, 69, 70);
    textAreaDevicesLarge.setColor(touchgfx::Color::getColorFromRGB(52, 75, 101));
    textAreaDevicesLarge.setLinespacing(0);
    Unicode::snprintf(textAreaDevicesLargeBuffer, TEXTAREADEVICESLARGE_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_P97C).getText());
    textAreaDevicesLarge.setWildcard(textAreaDevicesLargeBuffer);
    textAreaDevicesLarge.setTypedText(touchgfx::TypedText(T___SINGLEUSE_VTBC));
    containerLarge.add(textAreaDevicesLarge);

    textAreaRoomLarge.setPosition(3, 2, 120, 19);
    textAreaRoomLarge.setColor(touchgfx::Color::getColorFromRGB(52, 75, 101));
    textAreaRoomLarge.setLinespacing(0);
    textAreaRoomLarge.setTypedText(touchgfx::TypedText(T___SINGLEUSE_XE6F));
    containerLarge.add(textAreaRoomLarge);

    imageSliderLarge.setXY(2, 35);
    imageSliderLarge.setBitmap(touchgfx::Bitmap(BITMAP_MAIN_SLIDER_TEMP_ID));
    containerLarge.add(imageSliderLarge);

    textAreaDegreeLarge.setXY(57, 48);
    textAreaDegreeLarge.setColor(touchgfx::Color::getColorFromRGB(46, 64, 86));
    textAreaDegreeLarge.setLinespacing(0);
    textAreaDegreeLarge.setTypedText(touchgfx::TypedText(T___SINGLEUSE_BJOQ));
    containerLarge.add(textAreaDegreeLarge);

    add(containerLarge);

    imageSchedule.setXY(298, 39);
    imageSchedule.setBitmap(touchgfx::Bitmap(BITMAP_SCHEDULE_ICON_ID));
    add(imageSchedule);

    textAreaTemperature.setPosition(48, 46, 44, 27);
    textAreaTemperature.setColor(touchgfx::Color::getColorFromRGB(61, 82, 106));
    textAreaTemperature.setLinespacing(0);
    Unicode::snprintf(textAreaTemperatureBuffer, TEXTAREATEMPERATURE_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_4PDE).getText());
    textAreaTemperature.setWildcard(textAreaTemperatureBuffer);
    textAreaTemperature.setTypedText(touchgfx::TypedText(T___SINGLEUSE_GQOM));
    add(textAreaTemperature);

    textAreaHumidty.setPosition(48, 90, 44, 27);
    textAreaHumidty.setColor(touchgfx::Color::getColorFromRGB(61, 82, 106));
    textAreaHumidty.setLinespacing(0);
    Unicode::snprintf(textAreaHumidtyBuffer, TEXTAREAHUMIDTY_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_4OJ6).getText());
    textAreaHumidty.setWildcard(textAreaHumidtyBuffer);
    textAreaHumidty.setTypedText(touchgfx::TypedText(T___SINGLEUSE_H9W4));
    add(textAreaHumidty);

    textAreaSchedule.setXY(285, 10);
    textAreaSchedule.setColor(touchgfx::Color::getColorFromRGB(77, 108, 139));
    textAreaSchedule.setLinespacing(0);
    textAreaSchedule.setTypedText(touchgfx::TypedText(T___SINGLEUSE_SIW6));
    add(textAreaSchedule);

    textAreaScheduleDays.setXY(284, 95);
    textAreaScheduleDays.setColor(touchgfx::Color::getColorFromRGB(46, 65, 87));
    textAreaScheduleDays.setLinespacing(0);
    textAreaScheduleDays.setTypedText(touchgfx::TypedText(T___SINGLEUSE_YTVE));
    add(textAreaScheduleDays);

    textAreaScheduleTime.setXY(267, 111);
    textAreaScheduleTime.setColor(touchgfx::Color::getColorFromRGB(46, 65, 87));
    textAreaScheduleTime.setLinespacing(0);
    textAreaScheduleTime.setTypedText(touchgfx::TypedText(T___SINGLEUSE_HF53));
    add(textAreaScheduleTime);
}

RoomInfoBase::~RoomInfoBase()
{

}

void RoomInfoBase::initialize()
{

}
