/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/OvenSplashScreenBase.hpp>
#include <images/BitmapDatabase.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <touchgfx/Color.hpp>

OvenSplashScreenBase::OvenSplashScreenBase() :
    flexButtonCallback(this, &OvenSplashScreenBase::flexButtonCallbackHandler)
{
    setWidth(480);
    setHeight(272);
    background.setXY(0, 0);
    background.setBitmap(touchgfx::Bitmap(BITMAP_OVEN_POWER_BG_CLEAN_ID));
    add(background);

    textAreaHour.setPosition(129, 156, 100, 96);
    textAreaHour.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    textAreaHour.setLinespacing(0);
    textAreaHour.setTypedText(touchgfx::TypedText(T___SINGLEUSE_AZTP));
    add(textAreaHour);

    textAreaMinute.setPosition(251, 156, 100, 96);
    textAreaMinute.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    textAreaMinute.setLinespacing(0);
    textAreaMinute.setTypedText(touchgfx::TypedText(T___SINGLEUSE_BVWG));
    add(textAreaMinute);

    textAreaDivider.setPosition(229, 156, 22, 96);
    textAreaDivider.setColor(touchgfx::Color::getColorFromRGB(167, 228, 246));
    textAreaDivider.setLinespacing(0);
    textAreaDivider.setTypedText(touchgfx::TypedText(T___SINGLEUSE_X3W4));
    add(textAreaDivider);

    textAreaAmPm.setPosition(333, 212, 40, 29);
    textAreaAmPm.setColor(touchgfx::Color::getColorFromRGB(167, 228, 246));
    textAreaAmPm.setLinespacing(0);
    textAreaAmPm.setTypedText(touchgfx::TypedText(T___SINGLEUSE_ZVQC));
    add(textAreaAmPm);

    powerButton.setIconBitmaps(Bitmap(BITMAP_POWER_BUTTON_BIG_ID), Bitmap(BITMAP_POWER_BUTTON_PRESSED_BIG_ID));
    powerButton.setIconXY(170, 40);
    powerButton.setBitmaps(Bitmap(BITMAP_BTN_BG_ID), Bitmap(BITMAP_BTN_BG_ID));
    powerButton.setBitmapXY(0, 0);
    powerButton.setAction(flexButtonCallback);
    powerButton.setPosition(0, 0, 480, 272);
    add(powerButton);
}

OvenSplashScreenBase::~OvenSplashScreenBase()
{

}

void OvenSplashScreenBase::initialize()
{

}

void OvenSplashScreenBase::flexButtonCallbackHandler(const touchgfx::AbstractButtonContainer& src)
{
    if (&src == &powerButton)
    {
        //screenPressed
        //When powerButton clicked call virtual function
        //Call screenIsPressed
        screenIsPressed();
    }
}
