// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_80_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  40,  58,  56,   4,  49,   0,   0, 0x00 }, // zero
    {  1160, 0x0031,  23,  56,  55,   1,  32,   0,   1, 0x00 }, // one
    {  1832, 0x0032,  37,  57,  56,   4,  45,   0,   0, 0x00 }, // two
    {  2915, 0x0033,  36,  58,  56,   4,  45,   0,   0, 0x00 }, // three
    {  3959, 0x0034,  44,  55,  55,   3,  50,   1,   2, 0x00 }, // four
    {  5169, 0x0035,  35,  57,  55,   4,  43,   0,   0, 0x00 }, // five
    {  6195, 0x0036,  37,  58,  56,   5,  46,   0,   0, 0x00 }, // six
    {  7297, 0x0037,  36,  56,  55,   3,  41,   3,   1, 0x00 }, // seven
    {  8305, 0x0038,  39,  57,  56,   5,  49,   0,   0, 0x00 }, // eight
    {  9445, 0x0039,  37,  58,  56,   4,  46,   0,   0, 0x00 }, // nine
    { 10547, 0x003A,   9,  35,  35,   5,  19,   0,   0, 0x00 }, // colon
    { 10722, 0x003F,  35,  57,  57,   3,  40,   0,   0, 0x00 }  // question
};

// Exo2_Medium_80_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_80_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Exo2_Medium_80_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Exo2_Medium_80_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Exo2_Medium_80_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Exo2_Medium_80_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Exo2_Medium_80_4bpp();

touchgfx::GeneratedFont& getFont_Exo2_Medium_80_4bpp()
{
    static touchgfx::GeneratedFont Exo2_Medium_80_4bpp(glyphs_Exo2_Medium_80_4bpp, 12, 82, 80, 0, 0, 4, 1, 0, 0, unicodes_Exo2_Medium_80_4bpp, kerning_Exo2_Medium_80_4bpp, 63, 0, 0, 0);
    return Exo2_Medium_80_4bpp;
}
