/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/OvenWheelElementBase.hpp>
#include <images/BitmapDatabase.hpp>

OvenWheelElementBase::OvenWheelElementBase()
{
    setWidth(110);
    setHeight(110);
    imageMode.setXY(4, 7);
    imageMode.setBitmap(touchgfx::Bitmap(BITMAP_ICON_HOTAIR_ID));
    add(imageMode);

    imageSelectedMode.setXY(5, 6);
    imageSelectedMode.setBitmap(touchgfx::Bitmap(BITMAP_ICON_HOTAIR_ACTIVE_ID));
    imageSelectedMode.setVisible(false);
    add(imageSelectedMode);
}

OvenWheelElementBase::~OvenWheelElementBase()
{

}

void OvenWheelElementBase::initialize()
{

}
