/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/WasherWheelCenterItemBase.hpp>
#include <images/BitmapDatabase.hpp>

WasherWheelCenterItemBase::WasherWheelCenterItemBase()
{
    setWidth(100);
    setHeight(100);
    iconMode.setXY(0, 0);
    iconMode.setBitmap(touchgfx::Bitmap(BITMAP_ICON_CENTER_ACTIVEWEAR_MEDIUM_ID));
    add(iconMode);
}

WasherWheelCenterItemBase::~WasherWheelCenterItemBase()
{

}

void WasherWheelCenterItemBase::initialize()
{

}
