// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_20_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   5,   0,   0, 0x00 }, // space
    {     0, 0x003F,   9,  15,  15,   0,   9,   0,   0, 0x00 }, // question
    {    75, 0x0041,  13,  15,  15,   0,  12,   0,   0, 0x00 }, // A
    {   180, 0x0042,  11,  15,  15,   1,  12,   0,   0, 0x00 }, // B
    {   270, 0x0043,  12,  15,  15,   0,  12,   0,   0, 0x00 }, // C
    {   360, 0x0044,  13,  15,  15,   1,  14,   0,   0, 0x00 }, // D
    {   465, 0x0045,  10,  15,  15,   1,  11,   0,   0, 0x00 }, // E
    {   540, 0x0047,  13,  15,  15,   0,  13,   0,   0, 0x00 }, // G
    {   645, 0x0048,  13,  15,  15,   1,  15,   0,   0, 0x00 }, // H
    {   750, 0x0049,   4,  15,  15,   1,   6,   0,   0, 0x00 }, // I
    {   780, 0x004C,   9,  15,  15,   1,  10,   0,   0, 0x00 }, // L
    {   855, 0x004D,  15,  15,  15,   1,  17,   0,   0, 0x00 }, // M
    {   975, 0x004E,  12,  15,  15,   1,  14,   0,   0, 0x00 }, // N
    {  1065, 0x004F,  14,  15,  15,   0,  15,   0,   0, 0x00 }, // O
    {  1170, 0x0052,  11,  15,  15,   1,  12,   0,   0, 0x00 }, // R
    {  1260, 0x0053,  10,  15,  15,   0,  10,   0,   0, 0x00 }, // S
    {  1335, 0x0054,  11,  15,  15,   0,  11,   0,   0, 0x00 }, // T
    {  1425, 0x0055,  12,  15,  15,   1,  14,   0,   0, 0x00 }, // U
    {  1515, 0x0056,  13,  15,  15,   0,  12,   0,   0, 0x00 }, // V
    {  1620, 0x0057,  18,  15,  15,   0,  18,   0,   0, 0x00 }, // W
    {  1755, 0x0058,  12,  15,  15,   0,  12,   0,   0, 0x00 }  // X
};

// Asap_Bold_20_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_20_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_20_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_20_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_20_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_20_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_20_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_20_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_20_4bpp(glyphs_Asap_Bold_20_4bpp, 21, 20, 20, 0, 0, 4, 1, 0, 1, unicodes_Asap_Bold_20_4bpp, kerning_Asap_Bold_20_4bpp, 63, 0, 0, 0);
    return Asap_Bold_20_4bpp;
}
