// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_24_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x003F,  11,  17,  17,   0,  11,   0,   0, 0x00 }, // question
    {   102, 0x0041,  15,  17,  17,   0,  15,   0,   0, 0x00 }, // A
    {   238, 0x0042,  13,  17,  17,   1,  14,   0,   0, 0x00 }, // B
    {   357, 0x0043,  14,  17,  17,   1,  15,   0,   0, 0x00 }, // C
    {   476, 0x0045,  12,  17,  17,   1,  13,   0,   0, 0x00 }, // E
    {   578, 0x0048,  14,  17,  17,   2,  18,   0,   0, 0x00 }, // H
    {   697, 0x0049,   5,  17,  17,   1,   7,   0,   0, 0x00 }, // I
    {   748, 0x004B,  14,  17,  17,   1,  14,   0,   0, 0x00 }, // K
    {   867, 0x004D,  18,  17,  17,   1,  20,   0,   0, 0x00 }, // M
    {  1020, 0x004E,  15,  17,  17,   1,  17,   0,   0, 0x00 }, // N
    {  1156, 0x004F,  16,  17,  17,   1,  18,   0,   0, 0x00 }, // O
    {  1292, 0x0052,  14,  17,  17,   1,  15,   0,   0, 0x00 }, // R
    {  1411, 0x0054,  13,  17,  17,   0,  13,   0,   0, 0x00 }  // T
};

// Asap_Bold_24_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_24_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_24_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_24_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_24_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_24_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_24_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_24_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_24_4bpp(glyphs_Asap_Bold_24_4bpp, 13, 24, 24, 0, 0, 4, 1, 0, 1, unicodes_Asap_Bold_24_4bpp, kerning_Asap_Bold_24_4bpp, 63, 0, 0, 0);
    return Asap_Bold_24_4bpp;
}
