/* DO NOT EDIT THIS FILE */
/* This file is autogenerated by the text-database code generator */

#ifndef TOUCHGFX_APPLICATIONFONTPROVIDER_HPP
#define TOUCHGFX_APPLICATIONFONTPROVIDER_HPP

#include <touchgfx/FontManager.hpp>

namespace touchgfx
{
class FlashDataReader;
}

struct Typography
{
    static const touchgfx::FontId HEADLINE = 0;
    static const touchgfx::FontId RECIPELISTELEMENTHEADLINE = 1;
    static const touchgfx::FontId RECIPELISTELEMENTTEXT = 2;
    static const touchgfx::FontId INGREDIENTSTEXT = 3;
    static const touchgfx::FontId INGREDIENTSHEADLINE = 4;
    static const touchgfx::FontId STEPHEADLINE = 5;
    static const touchgfx::FontId NUTRITIONHEADLINE = 6;
    static const touchgfx::FontId NUTRITIONNAME = 7;
    static const touchgfx::FontId FANKNOB = 8;
    static const touchgfx::FontId TEMPERATUREWHEELCENTER = 9;
    static const touchgfx::FontId TEMPERATUREWHEEL = 10;
    static const touchgfx::FontId OVENMODE = 11;
    static const touchgfx::FontId OVENBOTTOMBAR = 12;
    static const touchgfx::FontId OVENTIMERWHEEL = 13;
    static const touchgfx::FontId OVENTEMPERATURESELECTED = 14;
    static const touchgfx::FontId OVENHEAT = 15;
    static const touchgfx::FontId OVENTIMERWHEELCENTER = 16;
    static const touchgfx::FontId HOMEUISPLASHTEMP = 17;
    static const touchgfx::FontId HOMEUISPLASHTEMPUNIT = 18;
    static const touchgfx::FontId HOMEUISPLASHROOM = 19;
    static const touchgfx::FontId HOMEUISPLASHHEAT = 20;
    static const touchgfx::FontId HOMEUISPLASHWAKEUP = 21;
    static const touchgfx::FontId HOMEUIWHEELBOTTOMLINE = 22;
    static const touchgfx::FontId HOMEUIWHEELBOTTOMLINESELECTEDITEM = 23;
    static const touchgfx::FontId HOMEUIWHEELHEADLINE = 24;
    static const touchgfx::FontId HOMEUIWHEELHEADLINESELECTEDITEM = 25;
    static const touchgfx::FontId HOMEUIMENUHEADLINE = 26;
    static const touchgfx::FontId HOMEUIWHEELWILDCARDSELECTEDITEM = 27;
    static const touchgfx::FontId HOMEUIINFO = 28;
    static const touchgfx::FontId DEVICENAME = 29;
    static const touchgfx::FontId DEVICEINFO = 30;
    static const touchgfx::FontId HOMEUIWHEELWILDCARD = 31;
    static const touchgfx::FontId OVENSPLASHCLOCK = 32;
    static const touchgfx::FontId OVENSPLASHAMPM = 33;
};

struct TypographyFontIndex
{
    static const touchgfx::FontId HEADLINE = 0;                          // SairaCondensed_Medium_22_4bpp
    static const touchgfx::FontId RECIPELISTELEMENTHEADLINE = 1;         // OpenSans_Semibold_20_4bpp
    static const touchgfx::FontId RECIPELISTELEMENTTEXT = 2;             // OpenSans_SemiboldItalic_13_4bpp
    static const touchgfx::FontId INGREDIENTSTEXT = 3;                   // OpenSans_Regular_16_4bpp
    static const touchgfx::FontId INGREDIENTSHEADLINE = 4;               // OpenSans_Italic_20_4bpp
    static const touchgfx::FontId STEPHEADLINE = 5;                      // OpenSans_Semibold_18_4bpp
    static const touchgfx::FontId NUTRITIONHEADLINE = 6;                 // OpenSans_Semibold_14_4bpp
    static const touchgfx::FontId NUTRITIONNAME = 7;                     // OpenSans_Regular_10_4bpp
    static const touchgfx::FontId FANKNOB = 8;                           // SairaSemiCondensed_Medium_34_4bpp
    static const touchgfx::FontId TEMPERATUREWHEELCENTER = 9;            // OpenSans_Semibold_26_4bpp
    static const touchgfx::FontId TEMPERATUREWHEEL = 10;                  // OpenSans_Semibold_23_4bpp
    static const touchgfx::FontId OVENMODE = 11;                          // Exo2_SemiBold_25_4bpp
    static const touchgfx::FontId OVENBOTTOMBAR = 12;                     // Exo2_Medium_34_4bpp
    static const touchgfx::FontId OVENTIMERWHEEL = 13;                    // Exo2_Medium_26_4bpp
    static const touchgfx::FontId OVENTEMPERATURESELECTED = 14;           // Exo2_Medium_40_4bpp
    static const touchgfx::FontId OVENHEAT = 15;                          // Exo2_Medium_18_4bpp
    static const touchgfx::FontId OVENTIMERWHEELCENTER = 16;              // Exo2_Medium_30_4bpp
    static const touchgfx::FontId HOMEUISPLASHTEMP = 17;                  // Asap_Bold_94_4bpp
    static const touchgfx::FontId HOMEUISPLASHTEMPUNIT = 18;              // Asap_Bold_25_4bpp
    static const touchgfx::FontId HOMEUISPLASHROOM = 19;                  // Asap_Bold_24_4bpp
    static const touchgfx::FontId HOMEUISPLASHHEAT = 20;                  // Asap_Bold_16_4bpp
    static const touchgfx::FontId HOMEUISPLASHWAKEUP = 21;                // Asap_Regular_26_4bpp
    static const touchgfx::FontId HOMEUIWHEELBOTTOMLINE = 22;             // Asap_Bold_10_4bpp
    static const touchgfx::FontId HOMEUIWHEELBOTTOMLINESELECTEDITEM = 23; // Asap_Bold_12_4bpp
    static const touchgfx::FontId HOMEUIWHEELHEADLINE = 24;               // Asap_Bold_14_4bpp
    static const touchgfx::FontId HOMEUIWHEELHEADLINESELECTEDITEM = 25;   // Asap_Bold_18_4bpp
    static const touchgfx::FontId HOMEUIMENUHEADLINE = 26;                // Asap_Bold_26_4bpp
    static const touchgfx::FontId HOMEUIWHEELWILDCARDSELECTEDITEM = 27;   // Asap_Bold_60_4bpp
    static const touchgfx::FontId HOMEUIINFO = 28;                        // Asap_Bold_22_4bpp
    static const touchgfx::FontId DEVICENAME = 29;                        // Asap_Bold_20_4bpp
    static const touchgfx::FontId DEVICEINFO = 24;                        // Asap_Bold_14_4bpp
    static const touchgfx::FontId HOMEUIWHEELWILDCARD = 30;               // Asap_Bold_40_4bpp
    static const touchgfx::FontId OVENSPLASHCLOCK = 31;                   // Exo2_Medium_80_4bpp
    static const touchgfx::FontId OVENSPLASHAMPM = 32;                    // Exo2_Medium_24_4bpp
    static const uint16_t NUMBER_OF_FONTS = 33;
};

class ApplicationFontProvider : public touchgfx::FontProvider
{
public:
    virtual touchgfx::Font* getFont(touchgfx::FontId typography);

    static void setFlashReader(touchgfx::FlashDataReader* /*flashReader*/)
    {
    }

    static touchgfx::FlashDataReader* getFlashReader()
    {
        return 0;
    }
};

#endif // TOUCHGFX_APPLICATIONFONTPROVIDER_HPP
