// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_SairaCondensed_Medium_22_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   4,   0,   0, 0x00 }, // space
    {     0, 0x002D,   5,   2,   8,   1,   7,   0,   0, 0x00 }, // hyphen
    {     6, 0x002E,   3,   3,   3,   1,   5,   0,   6, 0x00 }, // period
    {    12, 0x0030,   9,  16,  16,   1,  11,   0,   0, 0x00 }, // zero
    {    92, 0x0031,   5,  16,  16,   0,   6,   0,   0, 0x00 }, // one
    {   140, 0x0032,   9,  16,  16,   0,  10,   0,   0, 0x00 }, // two
    {   220, 0x0033,   9,  16,  16,   0,   9,   0,   0, 0x00 }, // three
    {   300, 0x0034,  10,  16,  16,   0,  10,   0,   0, 0x00 }, // four
    {   380, 0x0035,   8,  16,  16,   1,  10,   0,   0, 0x00 }, // five
    {   444, 0x0036,   9,  16,  16,   1,  10,   0,   0, 0x00 }, // six
    {   524, 0x0037,   9,  16,  16,   0,   9,   6,   1, 0x00 }, // seven
    {   604, 0x0038,   9,  16,  16,   1,  11,   0,   0, 0x00 }, // eight
    {   684, 0x0039,  10,  16,  16,   0,  10,   0,   0, 0x00 }, // nine
    {   764, 0x003A,   3,  12,  12,   1,   5,   0,   0, 0x00 }, // colon
    {   788, 0x0041,  11,  16,  16,   0,  11,   7,   7, 0x00 }, // A
    {   884, 0x0042,   9,  16,  16,   1,  11,   0,   0, 0x00 }, // B
    {   964, 0x0043,   8,  16,  16,   1,   9,   0,   0, 0x00 }, // C
    {  1028, 0x0044,   9,  16,  16,   1,  11,   0,   0, 0x00 }, // D
    {  1108, 0x0045,   8,  16,  16,   1,   9,   0,   0, 0x00 }, // E
    {  1172, 0x0046,   8,  16,  16,   1,   9,   0,   0, 0x00 }, // F
    {  1236, 0x0047,   9,  16,  16,   1,  11,   0,   0, 0x00 }, // G
    {  1316, 0x0048,  10,  16,  16,   1,  12,   0,   0, 0x00 }, // H
    {  1396, 0x0049,   3,  16,  16,   1,   5,   0,   0, 0x00 }, // I
    {  1428, 0x004A,   5,  16,  16,   0,   6,  14,   2, 0x00 }, // J
    {  1476, 0x004B,  10,  16,  16,   1,  11,   0,   0, 0x00 }, // K
    {  1556, 0x004C,   8,  16,  16,   1,   8,   0,   0, 0x00 }, // L
    {  1620, 0x004D,  13,  16,  16,   1,  15,   0,   0, 0x00 }, // M
    {  1732, 0x004E,  10,  16,  16,   1,  12,   0,   0, 0x00 }, // N
    {  1812, 0x004F,  10,  16,  16,   1,  11,   0,   0, 0x00 }, // O
    {  1892, 0x0050,   9,  16,  16,   1,  10,   0,   0, 0x00 }, // P
    {  1972, 0x0051,  10,  19,  16,   1,  11,   0,   0, 0x00 }, // Q
    {  2067, 0x0052,   9,  16,  16,   1,  11,   0,   0, 0x00 }, // R
    {  2147, 0x0053,   9,  16,  16,   0,  10,   0,   0, 0x00 }, // S
    {  2227, 0x0054,   9,  16,  16,   0,   9,   0,   0, 0x00 }, // T
    {  2307, 0x0055,   9,  16,  16,   1,  11,   0,   0, 0x00 }, // U
    {  2387, 0x0056,  10,  16,  16,   0,  10,  16,   1, 0x00 }, // V
    {  2467, 0x0057,  16,  16,  16,   0,  16,  17,   2, 0x00 }, // W
    {  2595, 0x0058,  11,  16,  16,   0,  11,   0,   0, 0x00 }, // X
    {  2691, 0x0059,  10,  16,  16,   0,  10,  19,   1, 0x00 }, // Y
    {  2771, 0x005A,   9,  16,  16,   0,   9,   0,   0, 0x00 }, // Z
    {  2851, 0x0061,   9,  12,  12,   0,   9,  20,   1, 0x00 }, // a
    {  2911, 0x0062,   8,  17,  17,   1,  10,   0,   0, 0x00 }, // b
    {  2979, 0x0063,   7,  12,  12,   0,   8,  21,   6, 0x00 }, // c
    {  3027, 0x0064,   9,  17,  17,   0,  10,  27,   6, 0x00 }, // d
    {  3112, 0x0065,   9,  12,  12,   0,   9,  33,   6, 0x00 }, // e
    {  3172, 0x0066,   6,  17,  17,   0,   6,   0,   0, 0x00 }, // f
    {  3223, 0x0067,   9,  16,  12,   0,  10,  39,   6, 0x00 }, // g
    {  3303, 0x0068,   8,  17,  17,   1,  10,   0,   0, 0x00 }, // h
    {  3371, 0x0069,   3,  17,  17,   1,   4,   0,   0, 0x00 }, // i
    {  3405, 0x006A,   5,  21,  17,  -1,   4,   0,   0, 0x00 }, // j
    {  3468, 0x006B,   8,  17,  17,   1,   9,   0,   0, 0x00 }, // k
    {  3536, 0x006C,   3,  17,  17,   1,   4,   0,   0, 0x00 }, // l
    {  3570, 0x006D,  13,  12,  12,   1,  15,  45,   1, 0x00 }, // m
    {  3654, 0x006E,   8,  12,  12,   1,  10,  46,   1, 0x00 }, // n
    {  3702, 0x006F,   9,  12,  12,   0,  10,  47,   6, 0x00 }, // o
    {  3762, 0x0070,   8,  16,  12,   1,  10,  53,   1, 0x00 }, // p
    {  3826, 0x0071,   9,  16,  12,   0,  10,  54,   6, 0x00 }, // q
    {  3906, 0x0072,   6,  12,  12,   1,   6,  60,   1, 0x00 }, // r
    {  3942, 0x0073,   8,  12,  12,   0,   8,  61,   4, 0x00 }, // s
    {  3990, 0x0074,   6,  16,  16,   0,   6,   0,   0, 0x00 }, // t
    {  4038, 0x0075,   8,  12,  12,   1,  10,  65,   1, 0x00 }, // u
    {  4086, 0x0076,   9,  12,  12,   0,   9,   0,   0, 0x00 }, // v
    {  4146, 0x0077,  14,  12,  12,   0,  14,   0,   0, 0x00 }, // w
    {  4230, 0x0078,   9,  12,  12,   0,   9,   0,   0, 0x00 }, // x
    {  4290, 0x0079,   8,  16,  12,   1,  10,  66,   1, 0x00 }, // y
    {  4354, 0x007A,   8,  12,  12,   0,   8,   0,   0, 0x00 }  // z
};

// SairaCondensed_Medium_22_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_SairaCondensed_Medium_22_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_SairaCondensed_Medium_22_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_SairaCondensed_Medium_22_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_SairaCondensed_Medium_22_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_SairaCondensed_Medium_22_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_SairaCondensed_Medium_22_4bpp();

touchgfx::GeneratedFont& getFont_SairaCondensed_Medium_22_4bpp()
{
    static touchgfx::GeneratedFont SairaCondensed_Medium_22_4bpp(glyphs_SairaCondensed_Medium_22_4bpp, 66, 26, 22, 0, 0, 4, 1, 1, 1, unicodes_SairaCondensed_Medium_22_4bpp, kerning_SairaCondensed_Medium_22_4bpp, 88, 0, 0, 0);
    return SairaCondensed_Medium_22_4bpp;
}
