// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_18_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   4,   0,   0, 0x00 }, // space
    {     0, 0x0030,  10,  13,  13,   0,  10,   0,   0, 0x00 }, // zero
    {    65, 0x0031,   9,  13,  13,   0,  10,   0,   0, 0x00 }, // one
    {   130, 0x0032,   9,  13,  13,   0,  10,   0,   0, 0x00 }, // two
    {   195, 0x0033,   9,  13,  13,   0,  10,   0,   0, 0x00 }, // three
    {   260, 0x0034,  10,  13,  13,   0,  10,   0,   0, 0x00 }, // four
    {   325, 0x0035,   9,  13,  13,   0,  10,   0,   0, 0x00 }, // five
    {   390, 0x0036,  10,  13,  13,   0,  10,   0,   0, 0x00 }, // six
    {   455, 0x0037,   9,  13,  13,   0,  10,   0,   0, 0x00 }, // seven
    {   520, 0x0038,  10,  13,  13,   0,  10,   0,   0, 0x00 }, // eight
    {   585, 0x0039,   9,  13,  13,   0,  10,   0,   0, 0x00 }, // nine
    {   650, 0x003F,   8,  13,  13,   0,   8,   0,   0, 0x00 }, // question
    {   702, 0x0041,  11,  13,  13,   0,  11,   0,   0, 0x00 }, // A
    {   780, 0x0042,  10,  13,  13,   1,  11,   0,   0, 0x00 }, // B
    {   845, 0x0043,  11,  13,  13,   0,  11,   0,   0, 0x00 }, // C
    {   923, 0x0044,  11,  13,  13,   1,  13,   0,   0, 0x00 }, // D
    {  1001, 0x0045,   9,  13,  13,   1,  10,   0,   0, 0x00 }, // E
    {  1066, 0x0046,   8,  13,  13,   1,   9,   0,   0, 0x00 }, // F
    {  1118, 0x0047,  11,  13,  13,   0,  12,   0,   0, 0x00 }, // G
    {  1196, 0x0048,  11,  13,  13,   1,  13,   0,   0, 0x00 }, // H
    {  1274, 0x0049,   3,  13,  13,   1,   5,   0,   0, 0x00 }, // I
    {  1300, 0x004B,  10,  13,  13,   1,  10,   0,   0, 0x00 }, // K
    {  1365, 0x004C,   8,  13,  13,   1,   9,   0,   0, 0x00 }, // L
    {  1417, 0x004D,  13,  13,  13,   1,  15,   0,   0, 0x00 }, // M
    {  1508, 0x004E,  11,  13,  13,   1,  13,   0,   0, 0x00 }, // N
    {  1586, 0x004F,  13,  13,  13,   0,  13,   0,   0, 0x00 }, // O
    {  1677, 0x0052,  10,  13,  13,   1,  11,   0,   0, 0x00 }, // R
    {  1742, 0x0053,   9,  13,  13,   0,   9,   0,   0, 0x00 }, // S
    {  1807, 0x0054,  10,  13,  13,   0,  10,   0,   0, 0x00 }, // T
    {  1872, 0x0056,  11,  13,  13,   0,  11,   0,   0, 0x00 }, // V
    {  1950, 0x00B0,   6,   6,  14,   0,   6,   0,   0, 0x00 }  // degree
};

// Asap_Bold_18_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_18_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_18_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_18_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_18_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_18_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_18_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_18_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_18_4bpp(glyphs_Asap_Bold_18_4bpp, 31, 18, 18, 0, 0, 4, 1, 0, 1, unicodes_Asap_Bold_18_4bpp, kerning_Asap_Bold_18_4bpp, 63, 0, 0, 0);
    return Asap_Bold_18_4bpp;
}
