// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_40_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   9,   0,   0, 0x00 }, // space
    {     0, 0x0030,  20,  28,  28,   2,  24,   0,   0, 0x00 }, // zero
    {   280, 0x0031,  12,  28,  28,   0,  16,   0,   1, 0x00 }, // one
    {   448, 0x0032,  19,  28,  28,   2,  23,   0,   0, 0x00 }, // two
    {   728, 0x0033,  18,  28,  28,   2,  22,   0,   0, 0x00 }, // three
    {   980, 0x0034,  23,  28,  28,   1,  25,   1,   3, 0x00 }, // four
    {  1316, 0x0035,  18,  28,  28,   2,  22,   0,   0, 0x00 }, // five
    {  1568, 0x0036,  19,  28,  28,   2,  23,   0,   0, 0x00 }, // six
    {  1848, 0x0037,  19,  28,  28,   1,  21,   4,   1, 0x00 }, // seven
    {  2128, 0x0038,  20,  28,  28,   2,  24,   0,   0, 0x00 }, // eight
    {  2408, 0x0039,  19,  28,  28,   2,  23,   0,   0, 0x00 }, // nine
    {  2688, 0x003F,  18,  29,  29,   1,  20,   0,   0, 0x00 }, // question
    {  2949, 0x0043,  20,  28,  28,   2,  23,   0,   0, 0x00 }, // C
    {  3229, 0x00B0,  11,  11,  29,   2,  14,   5,   1, 0x00 }  // degree
};

// Exo2_Medium_40_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Exo2_Medium_40_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Exo2_Medium_40_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Exo2_Medium_40_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Exo2_Medium_40_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Exo2_Medium_40_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Exo2_Medium_40_4bpp();

touchgfx::GeneratedFont& getFont_Exo2_Medium_40_4bpp()
{
    static touchgfx::GeneratedFont Exo2_Medium_40_4bpp(glyphs_Exo2_Medium_40_4bpp, 14, 40, 40, 0, 0, 4, 1, 0, 0, unicodes_Exo2_Medium_40_4bpp, kerning_Exo2_Medium_40_4bpp, 63, 0, 0, 0);
    return Exo2_Medium_40_4bpp;
}
