// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0020,   0,   0,   0,   0,   6,   0,   0, 0x00 }, // space
    {     0, 0x002D,   8,   3,   9,   0,   8,   0,   0, 0x00 }, // hyphen
    {    12, 0x0033,  12,  18,  18,   1,  14,   0,   0, 0x00 }, // three
    {   120, 0x0034,  14,  18,  18,   0,  14,   0,   0, 0x00 }, // four
    {   246, 0x003F,  12,  18,  18,   0,  12,   0,   0, 0x00 }, // question
    {   354, 0x0041,  16,  18,  18,   0,  16,   0,   0, 0x00 }, // A
    {   498, 0x0042,  14,  18,  18,   1,  15,   0,   0, 0x00 }, // B
    {   624, 0x0043,  15,  18,  18,   1,  16,   0,   0, 0x00 }, // C
    {   768, 0x0044,  16,  18,  18,   1,  18,   0,   0, 0x00 }, // D
    {   912, 0x0045,  13,  18,  18,   1,  14,   0,   0, 0x00 }, // E
    {  1038, 0x0048,  16,  18,  18,   2,  19,   0,   0, 0x00 }, // H
    {  1182, 0x0049,   5,  18,  18,   1,   7,   0,   0, 0x00 }, // I
    {  1236, 0x004B,  15,  18,  18,   1,  15,   0,   0, 0x00 }, // K
    {  1380, 0x004D,  20,  18,  18,   1,  22,   0,   0, 0x00 }, // M
    {  1560, 0x004E,  16,  18,  18,   1,  19,   0,   0, 0x00 }, // N
    {  1704, 0x004F,  17,  18,  18,   1,  19,   0,   0, 0x00 }, // O
    {  1866, 0x0050,  14,  18,  18,   1,  15,   0,   0, 0x00 }, // P
    {  1992, 0x0052,  15,  18,  18,   1,  16,   0,   0, 0x00 }, // R
    {  2136, 0x0053,  13,  18,  18,   0,  13,   0,   0, 0x00 }, // S
    {  2262, 0x0054,  15,  18,  18,   0,  14,   0,   0, 0x00 }, // T
    {  2406, 0x0055,  16,  18,  18,   1,  19,   0,   0, 0x00 }, // U
    {  2550, 0x0056,  16,  18,  18,   0,  16,   0,   0, 0x00 }  // V
};

// Asap_Bold_26_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_26_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_26_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_26_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_26_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_26_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_26_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_26_4bpp(glyphs_Asap_Bold_26_4bpp, 22, 26, 26, 0, 0, 4, 1, 0, 1, unicodes_Asap_Bold_26_4bpp, kerning_Asap_Bold_26_4bpp, 63, 0, 0, 0);
    return Asap_Bold_26_4bpp;
}
