// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_40_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  20,  28,  28,   1,  21,   0,   0, 0x00 }, // zero
    {   280, 0x0031,  19,  28,  28,   1,  21,   0,   0, 0x00 }, // one
    {   560, 0x0032,  19,  28,  28,   1,  21,   0,   0, 0x00 }, // two
    {   840, 0x0033,  19,  28,  28,   1,  21,   0,   0, 0x00 }, // three
    {  1120, 0x0034,  22,  28,  28,   0,  21,   0,   0, 0x00 }, // four
    {  1428, 0x0035,  19,  28,  28,   1,  21,   0,   0, 0x00 }, // five
    {  1708, 0x0036,  20,  28,  28,   1,  21,   0,   0, 0x00 }, // six
    {  1988, 0x0037,  19,  28,  28,   1,  21,   0,   0, 0x00 }, // seven
    {  2268, 0x0038,  20,  28,  28,   1,  21,   0,   0, 0x00 }, // eight
    {  2548, 0x0039,  19,  28,  28,   1,  21,   0,   0, 0x00 }, // nine
    {  2828, 0x003F,  17,  28,  28,   1,  18,   0,   0, 0x00 }  // question
};

// Asap_Bold_40_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_Asap_Bold_40_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_Asap_Bold_40_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_Asap_Bold_40_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_Asap_Bold_40_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_Asap_Bold_40_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_Asap_Bold_40_4bpp();

touchgfx::GeneratedFont& getFont_Asap_Bold_40_4bpp()
{
    static touchgfx::GeneratedFont Asap_Bold_40_4bpp(glyphs_Asap_Bold_40_4bpp, 11, 40, 40, 0, 0, 4, 1, 0, 1, unicodes_Asap_Bold_40_4bpp, kerning_Asap_Bold_40_4bpp, 63, 0, 0, 0);
    return Asap_Bold_40_4bpp;
}
