/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/OvenTemperatureContainerBase.hpp>
#include <images/BitmapDatabase.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <touchgfx/Color.hpp>

OvenTemperatureContainerBase::OvenTemperatureContainerBase()
{
    setWidth(480);
    setHeight(192);
    tempWheel.setXY(0, 32);
    tempWheel.setBitmap(touchgfx::Bitmap(BITMAP_TEMP_WHEEL_01_ID));
    add(tempWheel);

    selectedTemp.setPosition(157, 9, 136, 49);
    selectedTemp.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    selectedTemp.setLinespacing(0);
    Unicode::snprintf(selectedTempBuffer, SELECTEDTEMP_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_RDMG).getText());
    selectedTemp.setWildcard(selectedTempBuffer);
    selectedTemp.setTypedText(touchgfx::TypedText(T___SINGLEUSE_52RS));
    add(selectedTemp);

    ovenHeat.setXY(194, 161);
    ovenHeat.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    ovenHeat.setLinespacing(0);
    ovenHeat.setTypedText(touchgfx::TypedText(T___SINGLEUSE_8X03));
    add(ovenHeat);
}

OvenTemperatureContainerBase::~OvenTemperatureContainerBase()
{

}

void OvenTemperatureContainerBase::initialize()
{

}
