// Autogenerated, do not edit

#include <fonts/GeneratedFont.hpp>

FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_Semibold_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE = {
    {     0, 0x0030,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // zero
    {   126, 0x0031,   8,  18,  18,   2,  15,   0,   0, 0x00 }, // one
    {   198, 0x0032,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // two
    {   324, 0x0033,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // three
    {   450, 0x0034,  15,  18,  18,   0,  15,   0,   0, 0x00 }, // four
    {   594, 0x0035,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // five
    {   720, 0x0036,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // six
    {   846, 0x0037,  14,  18,  18,   0,  15,   0,   0, 0x00 }, // seven
    {   972, 0x0038,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // eight
    {  1098, 0x0039,  13,  18,  18,   1,  15,   0,   0, 0x00 }, // nine
    {  1224, 0x003F,  12,  18,  18,   0,  12,   0,   0, 0x00 }  // question
};

// OpenSans_Semibold_26_4bpp
FONT_TABLE_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::GlyphNode glyphs_OpenSans_Semibold_26_4bpp[] FONT_TABLE_LOCATION_FLASH_ATTRIBUTE;
FONT_GLYPH_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t unicodes_OpenSans_Semibold_26_4bpp_0[] FONT_GLYPH_LOCATION_FLASH_ATTRIBUTE;
FONT_SEARCHTABLE_LOCATION_FLASH_PRAGMA
KEEP extern const uint8_t* const unicodes_OpenSans_Semibold_26_4bpp[] FONT_SEARCHTABLE_LOCATION_FLASH_ATTRIBUTE = {
    unicodes_OpenSans_Semibold_26_4bpp_0
};
FONT_KERNING_LOCATION_FLASH_PRAGMA
KEEP extern const touchgfx::KerningNode kerning_OpenSans_Semibold_26_4bpp[] FONT_KERNING_LOCATION_FLASH_ATTRIBUTE;
touchgfx::GeneratedFont& getFont_OpenSans_Semibold_26_4bpp();

touchgfx::GeneratedFont& getFont_OpenSans_Semibold_26_4bpp()
{
    static touchgfx::GeneratedFont OpenSans_Semibold_26_4bpp(glyphs_OpenSans_Semibold_26_4bpp, 11, 26, 26, 0, 0, 4, 1, 0, 0, unicodes_OpenSans_Semibold_26_4bpp, kerning_OpenSans_Semibold_26_4bpp, 63, 0, 0, 0);
    return OpenSans_Semibold_26_4bpp;
}
